services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: moondesk_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-moondesk}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - moondesk_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: moondesk_mqtt
    ports:
      - "${MQTT_PORT:-1883}:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - moondesk_net

  redis:
    image: redis:alpine
    container_name: moondesk_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - moondesk_net


volumes:
  timescaledb_data:
  mosquitto_data:
  mosquitto_log:
  redis_data:

networks:
  moondesk_net:
    driver: bridge
