basePath: /
host: localhost:8080
info:
  contact:
    email: support@moondesk.io
    name: API Support
  description: High-throughput IoT ingestion and management platform.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Moondesk API
  version: "1.0"
paths: {}
swagger: "2.0"
